""" Error codes from AD LDAP Operations """

SUCCESS = 0
NO_SUCH_ATTRIBUTE = 16
UNDEFINED_TYPE = 17
CONSTRAINT_VIOLATION = 19
TYPE_OR_VALUE_EXISTS = 20
INVALID_SYNTAX = 21
INVALID_ARGUMENT = 22
NO_SUCH_OBJECT = 32
INSUFFICIENT_ACCESS = 50
UNWILLING_TO_PERFORM = 53
NAMING_VIOLATION = 64
OBJECT_CLASS_VIOLATION = 65
ALREADY_EXISTS = 68

MODIFY_ERRORS = [str(NO_SUCH_ATTRIBUTE), str(UNDEFINED_TYPE), str(CONSTRAINT_VIOLATION),
                 str(TYPE_OR_VALUE_EXISTS), str(INVALID_SYNTAX), str(INSUFFICIENT_ACCESS),
                 str(UNWILLING_TO_PERFORM), str(OBJECT_CLASS_VIOLATION), str(ALREADY_EXISTS)]

MOVE_ERRORS = [str(INSUFFICIENT_ACCESS), str(NAMING_VIOLATION), str(ALREADY_EXISTS)]
